### PR TITLE
Add mapbox view

### PR DESCRIPTION
**Pull request by devonpmack**
Fix https://github.com/cuhacking/atlas-editor/issues/1
image

### CODE REVIEW

**Review by dellisd — COMMENTED** [review]
Are you going to write your own React wrapper for Mapbox? There are already several out there.

**Comment by devonpmack** [comment]
We can use one once we need it or would you prefer to have it now

**Comment by dellisd** [comment]
I'd prefer to have it now

**Comment by devonpmack** [comment]
Hmm I tried two of them, one doesn't have types and the other `react-mapbox-gl` doesn't play nice with electron.

**Comment by devonpmack** [comment]
Unless someone wants to go indepth into this I say we keep the custom wrapper for now

**Comment by dellisd** [comment]
> Hmm I tried two of them, one doesn't have types and the other `react-mapbox-gl` doesn't play nice with electron.

There's also https://github.com/visgl/react-map-gl, not sure if you've looked at it. I know this one has types available (via DefiniteyTyped) although it removes all animated transitions..

But between maintaining your own wrapper vs just writing types for that other one, it's up to you. It'll be your responsibility.

**Review by dellisd — APPROVED** [review]

**Review by deenhaque — APPROVED** [review]

**Comment by devonpmack** [comment]
Ok I tried that package @dellisd and I think it's also broken with electron 😢 It renders but the map is blank, even with api token.

**Pull request merged**
